  
name: testGithubApp

on: 
    push:
        paths:
            - 'test/**'

jobs:
    test:
      runs-on: [ubuntu-latest]
      steps:
        - name: Get Token
          id: get_workflow_token
          uses: peter-murray/workflow-application-token-action@v1
          with:
            application_id: ${{ secrets.APPLICATION_ID }}
            application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

        - name: Use Application Token to repository dispatch
          run: echo ${{ steps.get_workflow_token.outputs.token }}
#           uses: peter-evans/repository-dispatch@v1
#           env:
#             GITHUB_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
#           with:
#             repository: lauracavaliere/code
#             event-type: repository_trigger
