  
name: testGithubApp

on: 
    workflow_dispatch:

jobs:
    test:
      runs-on: [ubuntu-latest]
      steps:
        - name: Get Token
          id: get_workflow_token
          uses: peter-murray/workflow-application-token-action@v1
          with:
            application_id: ${{ secrets.APPLICATION_ID }}
            application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}
            
#        - name: Repository Dispatch
#          uses: peter-evans/repository-dispatch@v1
#          env:
#             GITHUB_APPS_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
#          with:
#            token: ${{ env.GITHUB_APPS_TOKEN }}
#            repository: icub-training/test-app
#            event-type: repository_trigger        

        - name: Commit to icub-training
          uses: actions/checkout@v2
          env:
             GITHUB_APPS_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
          with:
            token: ${{ env.GITHUB_APPS_TOKEN }}
            repository: icub-training/test-app
            
        - name: Push
          run: | 
            ls 

