  
name: testGithubApp

on: 
    workflow_dispatch:

jobs:
    test:
      runs-on: [ubuntu-latest]
      steps:
        - name: Get Token
          id: get_workflow_token
          uses: machine-learning-apps/actions-app-token@master
          with:
            APP_PEM: ${{ secrets.APPLICATION_PRIVATE_KEY }}
            APP_ID: ${{ secrets.APPLICATION_ID }}
            
#        - name: Repository Dispatch
#          uses: peter-evans/repository-dispatch@v1
#          env:
#             GITHUB_APPS_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
#          with:
#            token: ${{ env.GITHUB_APPS_TOKEN }}
#            repository: icub-training/test-app
#            event-type: repository_trigger        

            
        - name: Commit to icub-training
          uses: actions/checkout@v2
          env:
             GITHUB_APPS_TOKEN: ${{ steps.get_workflow_token.outputs.token }}
          with:
            token: ${{ env.GITHUB_APPS_TOKEN }}
            repository: icub-training/test-app
            


